### ISSUE TITLE
no data in influxdb 2

### ISSUE THREAD

**Issue by GieGit** [smilebasti/npmGrafStats#4] opened 2023-04-30 08:03 UTC
i have installed the tool. unfortunately no data is written to the bucket. i can't find any error message in the logs either

**Comment by smilebasti** [comment] 2023-05-01 09:37
Hi,
thanks for the hint to add some debug logs. 

Until i add them have you checked if you set the Organization, Bucket Host and Token correctly?

**Comment by GieGit** [comment] 2023-05-01 15:12
Hi yes I have checked all the data again and they are all correctly in the stack.
I have also created a new API Token which only has rights to the bucket.

**Comment by smilebasti** [comment] 2023-05-03 12:57
Ok i have tried to reproduce the error but wasn't able to.
I pulled the latest docker-images of nginx-reverse-proxy-manager, npmgrafstats, influxdb and even grafana. 
I tried entering wrong credentials for influx in the npmgrafstats config, but that has thrown me an error-message. I tested the api token with only write access for npmgrafstats-bucket and it worked.

Can you explain a little bit more? Which version of influxdb and npm are you running? Is influxdb on same host and in Docker?Has influxdb any error/access logs? Did you recreate the npmgrafstats container after changing the config?

**Comment by GieGit** [comment] 2023-05-05 17:46
Hi thanks for your responce.
i have the following versions
influxdb : v2.6.1
npm: v2.10.2
**Is influxdb on the same host and in Docker:** No, influxdb is installed on its own server.
**Did you recreate the npmgrafstats container after changing the configuration?** Yes I deleted the images and pulled it again from the docker hub

**Comment by smilebasti** [comment] 2023-05-11 08:51
I am running the same setup but tried to recreate everything. It worked for.

If you see this in your logs it should work because no connection error occurs and the data is send.
![image](https://github.com/smilebasti/npmGrafStats/assets/60941345/8557202c-1792-435d-b660-abd9c7d4689d)

I think it has to do with your Influxdb but i don't know.
I'm closing this issue but if you have any further information you can reopen it.

**Closed by smilebasti** 2023-05-11 08:51 UTC
